[project]
name = "master-thesis-sli0124"
version = "0.1.0"
description = "Master thesis project for time series forecasting"
requires-python = ">=3.12"

dependencies = [
    "pandas",
    "tqdm",
    "requests",
    "openmeteo-requests",
    "retry-requests",
    "matplotlib",
    "seaborn",
    "xlrd",
    "openpyxl",
    "scikit-learn",
    "huggingface-hub",
    "granite-tsfm",
    "chronos-forecasting",
    "uni2ts",
    "mlflow",
    "setuptools<81",
    "ruff",
    "ipykernel",
    "black",
    "black[jupyter]",
    "torchview",
    "graphviz",
    "statsmodels",
]

[project.optional-dependencies]
cpu = ["torch"]
cu126 = ["torch"]
cu130 = ["torch"]

[tool.uv]
conflicts = [[{ extra = "cpu" }, { extra = "cu126" }, { extra = "cu130" }]]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu126", extra = "cu126" },
    { index = "pytorch-cu130", extra = "cu130" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.setuptools]
packages = ["data", "notebooks", "src"]

[tool.ruff]
line-length = 88

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # import sorting
    "B",   # bugbear
    "UP",  # pyupgrade
    "SIM", # simplifications
]

ignore = ["E501"] # line length handled by black

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88
