[project]
name = "master-thesis-sli0124"
version = "0.1.0"
description = "Master thesis project for time series forecasting"
requires-python = ">=3.12"

dependencies = [
    "torch",
    "pandas",
    "tqdm",
    "requests",
    "openmeteo-requests",
    "retry-requests",
    "matplotlib",
    "seaborn",
    "xlrd",
    "openpyxl",
    "scikit-learn",
    "huggingface-hub",
    "chronos-forecasting",
    "uni2ts",
    "lag-llama @ git+https://github.com/time-series-foundation-models/lag-llama.git",
    "timesfm[torch]",
]

# add same thing for different CUDA versions if needed
[tool.uv.sources]
torch = [{ index = "pytorch-cu130" }]
torchvision = [{ index = "pytorch-cu130" }]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[project.optional-dependencies]
dev = [
    "ruff",
    "ipykernel",
]

[tool.setuptools]
packages = ["data", "models", "pipeline", "notebooks"]

[tool.ruff]
line-length = 88

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "W505", # doc-line-too-long
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88
